### ISSUE TITLE
Epic: test for recoveries and data completeness after component failures

### ISSUE THREAD

**Issue by stepashka** [zenithdb/zenith#1130]
this should run on staging environment

implementation for this could overlap with #890 and maybe also zenithdb/console#423

- [ ] create a tool that can create a cluster, authenticate and establish a connection, start writing data (e.g. every second)
- [ ] start killing components (shut down the process or the whole host) of the system and bringing them back after a short while (manually at first)
- [ ] check that after component recovered, the cluster can start and that no data is lost
- [ ] automatically kill components on staging on schedule?

**Comment by kelvich** [comment]
Some context: with @cicdteam he had an implementation idea for the first tick here which can be also useful for capacity testing (#890):

`cloud_bench -i --rate=10 -j 5 -n 1000` creates 1000 clusters (e.g. bench_cluster_${i}) using 5 parallel jobs with each spawning 10 requests/sec.
`cloud_bench -n 1000 ...` runs some simple load on some the cluster. Exact grammar is to be defined, but would be good to define frequency so that we can keep some fixed percentage of clusters alive.

So the first item in this list could be the first single-threaded step towards the #890. But if we want to get there it is makes sense to write that tool in golang. Some python examples of the same behavior (create user, create cluster, but without using proxy) lies here: https://github.com/zenithdb/console/tree/main/tests_e2e

**Comment by hlinnaka** [comment]
I created https://github.com/zenithdb/console/pull/514 to address this, but it is not in a committable state. It helped to reproduce issue #1140, so it was useful already. I don't plan to work any further on this, so I'm unassigning myself.
