### ISSUE TITLE
Epic: Write Throughput — define metrics, define and achieve launch objectives

### ISSUE THREAD

**Issue by stepashka** [zenithdb/zenith#1467]
To prepare for the work on this epic we need to..
- [ ] define and collect the Write Throughput metrics
- [ ] collect the Write Throughput from both zenith and vanilla postgres for comparison and benchmark

Once we start collecting these measurements, we'd set a goal for them for the Technical Preview.
Below are the areas on what can help us achieve those goals.
- [ ] WAL record decoding
- [ ] Storing WAL record in in-memory layer
- [ ] In-memory layer flushing
- [ ] Compaction
- [ ] Image layer creation
- [ ] #1359
- [ ] #1357
- [ ] #1355

**Comment by hlinnaka** [comment]
Also related:

https://github.com/neondatabase/neon/issues/1773

**Comment by shanyp** [comment]
@problame this is more than a year old, please see what needs still to be considered

**Comment by stepashka** [comment]
renamed because we're currenlty post launch that the title was referring to :)
