### ISSUE TITLE
Epic: pre-lauch QA

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#890]
Tests to perform before launch:

- [ ] test with many active tenants
- [ ] cloud_bench: create 10 clusters/sec for one hour
- [ ] cloud_bench: determine how much active tenants pageserver can handle (active == 1 pgbench connection)
- [ ] select proper node size/type for safekeepers
- [ ] clickhouse 100gb dataset test
- [ ] test for limits (storage size, wal size) exhaustion

**Comment by antonyc** [comment]
We probably should use [circuit breaker](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/dn589784(v=pandp.10)?redirectedfrom=MSDN) at some point here, to ensure we do not break our stands.
There are [gobreaker](https://github.com/sony/gobreaker) and [hystrix-go](https://github.com/afex/hystrix-go) to help.

**Comment by antonyc** [comment]
The interface for now is like this:


init
```
./cloudbench --server="http://localhost:3000/" --token="8ar9t94zztf33t1i3vxejqn0t5x860b55xkmzmvqc6vshy5hi06nslxiz9oufawv" init active_tenants --max=3


2022-03-28T11:49:12.421Z	DEBUG	starting to execute init load of 3 pieces
2022-03-28T11:49:12.421Z	DEBUG	Will execute PGPASSWORD=ed45c03fbcf5661efbcc5fc205bcfc8176eaaeeb43e3221d3ba849ff806c pgbench --initialize --scale 10 --host 127.0.0.1 --port 4432 --username dpvqycwxeg@zenith active_tenants-1
2022-03-28T11:49:12.421Z	DEBUG	Will execute PGPASSWORD=6163ddeca47aadf5faf3d583be8c782d41640577cfbb5f2148648b42f444 pgbench --initialize --scale 10 --host 127.0.0.1 --port 4432 --username dpvqycwxeg@zenith active_tenants-0
2022-03-28T11:49:12.421Z	DEBUG	Will execute PGPASSWORD=e130844323f0f8a016686d467fcde2ecb363b4f52e0a3da9c9e89d901e52 pgbench --initialize --scale 10 --host 127.0.0.1 --port 4432 --username dpvqycwxeg@zenith active_tenants-2
2022-03-28T11:49:49.026Z	INFO	pgbench finished successfully
2022-03-28T11:49:49.026Z	DEBUG	pgbench output: "dropping old tables...\nNOTICE:  table \"pgbench_accounts\" does not exist, skipping\nNOTICE:  table \"pgbench_branches\" does not exist, skipping\nNOTICE:  table \"pgbench_history\" does not exist, skipping\nNOTICE:  table \"pgbench_tellers\" does not exist, skipping\ncreating tables...\ngenerating data...\n100000 of 1000000 tuples (10%) done (elapsed 0.04 s, remaining 0.38 s)\n200000 of 1000000 tuples (20%) done (elapsed 0.08 s, remaining 0.31 s)\n300000 of 1000000 tuples (30%) done (elapsed 0.12 s, remaining 0.28 s)\n400000 of 1000000 tuples (40%) done (elapsed 0.15 s, remaining 0.23 s)\n500000 of 1000000 tuples (50%) done (elapsed 0.19 s, remaining 0.19 s)\n600000 of 1000000 tuples (60%) done (elapsed 0.22 s, remaining 0.15 s)\n700000 of 1000000 tuples (70%) done (elapsed 0.25 s, remaining 0.11 s)\n800000 of 1000000 tuples (80%) done (elapsed 0.28 s, remaining 0.07 s)\n900000 of 1000000 tuples (90%) done (elapsed 0.31 s, remaining 0.03 s)\n1000000 of 1000000 tuples (100%) done (elapsed 0.34 s, remaining 0.00 s)\nvacuuming...\ncreating primary keys...\ndone.\n"
2022-03-28T11:49:49.026Z	DEBUG	load unit finished
2022-03-28T11:49:49.030Z	INFO	pgbench finished successfully
2022-03-28T11:49:49.030Z	DEBUG	pgbench output: "dropping old tables...\nNOTICE:  table \"pgbench_accounts\" does not exist, skipping\nNOTICE:  table \"pgbench_branches\" does not exist, skipping\nNOTICE:  table \"pgbench_history\" does not exist, skipping\nNOTICE:  table \"pgbench_tellers\" does not exist, skipping\ncreating tables...\ngenerating data...\n100000 of 1000000 tuples (10%) done (elapsed 0.03 s, remaining 0.23 s)\n200000 of 1000000 tuples (20%) done (elapsed 0.05 s, remaining 0.22 s)\n300000 of 1000000 tuples (30%) done (elapsed 0.09 s, remaining 0.22 s)\n400000 of 1000000 tuples (40%) done (elapsed 0.12 s, remaining 0.18 s)\n500000 of 1000000 tuples (50%) done (elapsed 0.15 s, remaining 0.15 s)\n600000 of 1000000 tuples (60%) done (elapsed 0.18 s, remaining 0.12 s)\n700000 of 1000000 tuples (70%) done (elapsed 0.21 s, remaining 0.09 s)\n800000 of 1000000 tuples (80%) done (elapsed 0.24 s, remaining 0.06 s)\n900000 of 1000000 tuples (90%) done (elapsed 0.27 s, remaining 0.03 s)\n1000000 of 1000000 tuples (100%) done (elapsed 0.30 s, remaining 0.00 s)\nvacuuming...\ncreating primary keys...\ndone.\n"
2022-03-28T11:49:49.030Z	DEBUG	load unit finished
2022-03-28T11:49:49.075Z	INFO	pgbench finished successfully
2022-03-28T11:49:49.076Z	DEBUG	pgbench output: "dropping old tables...\nNOTICE:  table \"pgbench_accounts\" does not exist, skipping\nNOTICE:  table \"pgbench_branches\" does not exist, skipping\nNOTICE:  table \"pgbench_history\" does not exist, skipping\nNOTICE:  table \"pgbench_tellers\" does not exist, skipping\ncreating tables...\ngenerating data...\n100000 of 1000000 tuples (10%) done (elapsed 0.04 s, remaining 0.32 s)\n200000 of 1000000 tuples (20%) done (elapsed 0.07 s, remaining 0.27 s)\n300000 of 1000000 tuples (30%) done (elapsed 0.09 s, remaining 0.22 s)\n400000 of 1000000 tuples (40%) done (elapsed 0.12 s, remaining 0.19 s)\n500000 of 1000000 tuples (50%) done (elapsed 0.15 s, remaining 0.15 s)\n600000 of 1000000 tuples (60%) done (elapsed 0.18 s, remaining 0.12 s)\n700000 of 1000000 tuples (70%) done (elapsed 0.21 s, remaining 0.09 s)\n800000 of 1000000 tuples (80%) done (elapsed 0.25 s, remaining 0.06 s)\n900000 of 1000000 tuples (90%) done (elapsed 0.28 s, remaining 0.03 s)\n1000000 of 1000000 tuples (100%) done (elapsed 0.32 s, remaining 0.00 s)\nvacuuming...\ncreating primary keys...\ndone.\n"
2022-03-28T11:49:49.076Z	DEBUG	load unit finished
2022-03-28T11:49:49.076Z	INFO	all done successfully
ubuntu@ip-172-31-26-161:~/zenithdb/console/bench/cmd/cloudbench$
```

run
```
./cloudbench --server="http://localhost:3000/" --token="8ar9t94zztf33t1i3vxejqn0t5x860b55xkmzmvqc6vshy5hi06nslxiz9oufawv" tests active_tenants --max=3


2022-03-28T11:50:12.295Z	DEBUG	starting to execute work load of 3 pieces
2022-03-28T11:50:12.295Z	DEBUG	Will execute PGPASSWORD=6c825de8d60c753664d257ee2b6cd6ed7ae7c17f51b3a5b469b1cdec65c0 pgbench --scale 10 --host 127.0.0.1 --port 4432 --username dpvqycwxeg@zenith active_tenants-0
2022-03-28T11:50:12.295Z	DEBUG	Will execute PGPASSWORD=40f0bd78c7b9e98e8db4d5f931da10c66b848b3df966bce91d670c47542f pgbench --scale 10 --host 127.0.0.1 --port 4432 --username dpvqycwxeg@zenith active_tenants-1
2022-03-28T11:50:12.295Z	DEBUG	Will execute PGPASSWORD=673d9b5936bc99713d329338daa578dc286c4562e4af0d8aed524a5515c3 pgbench --scale 10 --host 127.0.0.1 --port 4432 --username dpvqycwxeg@zenith active_tenants-2
2022-03-28T11:50:12.459Z	INFO	pgbench finished successfully
2022-03-28T11:50:12.459Z	DEBUG	pgbench output: "scale option ignored, using count from pgbench_branches table (10)\nstarting vacuum...end.\ntransaction type: <builtin: TPC-B (sort of)>\nscaling factor: 10\nquery mode: simple\nnumber of clients: 1\nnumber of threads: 1\nnumber of transactions per client: 10\nnumber of transactions actually processed: 10/10\nlatency average = 9.198 ms\ntps = 108.715539 (including connections establishing)\ntps = 121.827204 (excluding connections establishing)\n"
2022-03-28T11:50:12.459Z	DEBUG	load unit finished
2022-03-28T11:50:12.459Z	INFO	pgbench finished successfully
2022-03-28T11:50:12.459Z	DEBUG	pgbench output: "scale option ignored, using count from pgbench_branches table (10)\nstarting vacuum...end.\ntransaction type: <builtin: TPC-B (sort of)>\nscaling factor: 10\nquery mode: simple\nnumber of clients: 1\nnumber of threads: 1\nnumber of transactions per client: 10\nnumber of transactions actually processed: 10/10\nlatency average = 9.230 ms\ntps = 108.343261 (including connections establishing)\ntps = 121.325912 (excluding connections establishing)\n"
2022-03-28T11:50:12.459Z	DEBUG	load unit finished
2022-03-28T11:50:12.474Z	INFO	pgbench finished successfully
2022-03-28T11:50:12.474Z	DEBUG	pgbench output: "scale option ignored, using count from pgbench_branches table (10)\nstarting vacuum...end.\ntransaction type: <builtin: TPC-B (sort of)>\nscaling factor: 10\nquery mode: simple\nnumber of clients: 1\nnumber of threads: 1\nnumber of transactions per client: 10\nnumber of transactions actually processed: 10/10\nlatency average = 9.175 ms\ntps = 108.993442 (including connections establishing)\ntps = 121.316010 (excluding connections establishing)\n"
2022-03-28T11:50:12.474Z	DEBUG	load unit finished
2022-03-28T11:50:12.474Z	INFO	all done successfully
ubuntu@ip-172-31-26-161:~/zenithdb/console/bench/cmd/cloudbench$
```

**Comment by antonyc** [comment]
Planning to make a new environment to run cloudbench against.
