### ISSUE TITLE
Epic: documentation

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#891]
Documentation sections:

- [ ] Setup docs auto-generation from zenith repo
- [ ] Tech overview docs. Same level of granularity as https://apple.github.io/foundationdb/technical-overview.html
- [ ] Pages for all things mentioned on landing: 3 big features (scalability, storage, branches), 6 smaller features
- [ ] Roadmap page
- [ ] Describe connection options and their security
- [ ] Describe free tier limits
- [ ] Integration examples: rails / django / prisma / etc
- [ ] Integration examples: cloudflare workers / hasura / etc

Blog posts content plan:
- [ ] Welcome: team, mission what we have done since March
- [ ] Separation of storage and compute (why bother, pros/cons) and tech overview
- [ ] Safekeepers story and TLA
- [ ] Storage modelling -- models, pictures and results
- [ ] Cluster quick (github link) connect -- how we iterated on that idea
- [ ] Security story and avoiding passwords -- scram mitm, github, sessions
- [ ] Compute node on wasm

**Comment by stepashka** [comment]
https://hackmd.io/
